name: Run Postman tests with Newman

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Newman
      run: |
        npm install -g newman

    - name: Run Postman tests
      run: |
        newman run path/to/Postman_Practice.postman_collection.json -e path/to/Article_environment.postman_environment.json
        newman run path/to/Postman_Practice.postman_collection.json -e path/to/Sign_up_environment.postman_environment.json
        newman run path/to/Postman_Practice.postman_collection.json -e path/to/User_sign_in_environment.postman_environment.json
      
